apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - dns-service-job.yaml
  - networkpolicy-connect-job.yaml
  - networkpolicy-deny-iperf3-ingress.yaml
  - networkpolicy-allow-policy-check.yaml
