name: kube-linter

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  kube-linter:
    name: kube-linter
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Run kube-linter
        uses: stackrox/kube-linter-action@v1.0.4
        with:
          directory: deploy/
          config: .kube-linter.yaml
